In [1]:
import pandas as pd
df=pd.read_csv('titanic.csv')

In [19]:
df

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [20]:
df.columns

Index(['Pclass', 'Sex', 'Age', 'Fare', 'Survived'], dtype='object')

In [18]:
df.drop(['PassengerId', 'Name','SibSp', 'Parch',
       'Ticket','Cabin', 'Embarked'],axis=1)
df

KeyError: "['PassengerId' 'Name' 'SibSp' 'Parch' 'Ticket' 'Cabin' 'Embarked'] not found in axis"

In [21]:
inp=df.drop(['Survived'],axis=1)
target=df.Survived
inp

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [9]:
dummies=pd.get_dummies(inp.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [22]:
inp=pd.concat([inp,dummies],axis=1)

In [23]:
inp

Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [26]:
inp.drop(['Sex','male'],axis=1,inplace=True)

In [27]:
inp

Pclass   Age     Fare  female
0         3  22.0   7.2500       0
1         1  38.0  71.2833       1
2         3  26.0   7.9250       1
3         1  35.0  53.1000       1
4         3  35.0   8.0500       0
..      ...   ...      ...     ...
886       2  27.0  13.0000       0
887       1  19.0  30.0000       1
888       3   NaN  23.4500       1
889       1  26.0  30.0000       0
890       3  32.0   7.7500       0

[891 rows x 4 columns]

In [29]:
inp.columns[inp.isna().any()]

Index(['Age'], dtype='object')

In [30]:
inp.Age=inp.Age.fillna(inp.Age.mean())

In [31]:
inp.columns[inp.isna().any()]

Index([], dtype='object')

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(inp,target,test_size=0.3)

In [35]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [36]:
model.fit(X_train,y_train)

GaussianNB()

In [37]:
model.score(X_test,y_test)

0.7873134328358209

In [40]:
model.predict_proba(X_test[:10])

array([[0.96708134, 0.03291866],
       [0.24138947, 0.75861053],
       [0.26505494, 0.73494506],
       [0.00486598, 0.99513402],
       [0.92826878, 0.07173122],
       [0.97084845, 0.02915155],
       [0.97246863, 0.02753137],
       [0.27616182, 0.72383818],
       [0.48231956, 0.51768044],
       [0.42248092, 0.57751908]])

In [41]:
model.predict(X_test[:10])

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [43]:
X_test[:10]

Pclass   Age      Fare  female
90        3  29.0    8.0500       0
446       2  13.0   19.5000       1
417       2  18.0   13.0000       1
373       1  22.0  135.6333       0
361       2  29.0   27.7208       0
661       3  40.0    7.2250       0
222       3  51.0    8.0500       0
56        2  21.0   10.5000       1
100       3  28.0    7.8958       1
156       3  16.0    7.7333       1

In [44]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.792     , 0.752     , 0.808     , 0.78225806, 0.75      ])