In [1]:
import pandas as pd
df=pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [4]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [9]:
#Convert a collection of text documents to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x=vectorizer.fit_transform(X_train.values)

In [10]:
x

<4457x7784 sparse matrix of type '<class 'numpy.int64'>'
	with 59412 stored elements in Compressed Sparse Row format>

In [11]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
'''The multinomial Naive Bayes classifier is suitable for classification with discrete features 
(e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts'''
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x,y_train)

MultinomialNB()

In [20]:
emails = [
    'PUBG Mobile becomes the highest-earning game in the world in May 2020'
]
emails_count = vectorizer.transform(emails)

In [21]:
model.predict(emails_count)

array([0], dtype=int64)

In [16]:
x_test=vectorizer.transform(X_test)

In [17]:
model.score(x_test,y_test)

0.989237668161435

In [22]:
#Pipeline can be used to chain multiple estimators into one.
#This is useful as there is often a fixed sequence of steps in processing the data, 
#for example feature selection, normalization and classification.
#he Pipeline is built using a list of (key, value) pairs, 
#where the key is a string containing the name you want to give this step and value is an estimator object:

In [24]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),
             ('nb',MultinomialNB())])

In [25]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [26]:
clf.score(X_test,y_test)

0.989237668161435

In [27]:
clf.predict(emails)

array([0], dtype=int64)